// Generated by CoffeeScript 1.10.0
var cards, createCardName, express, resetCards, router;

express = require('express');

router = express.Router();

createCardName = function() {
  var position;
  position = Math.floor(Math.random() * cards.length);
  return cards.splice(position, 1);
};

resetCards = function() {
  var i, k, results;
  results = [];
  for (i = k = 1; k <= 13; i = k += 1) {
    cards[i - 1] = "club" + i;
    cards[i + 12] = "dmnd" + i;
    cards[i + 25] = "hart" + i;
    cards[i + 38] = "spad" + i;
    if (i < 3) {
      results.push(cards[i + 51] = "joke" + i);
    } else {
      results.push(void 0);
    }
  }
  return results;
};

cards = [];

resetCards();

router.route('/randomcard').get(function(req, res) {
  var cardNames, i, j, k, l;
  cardNames = {};
  for (i = k = 1; k <= 6; i = k += 1) {
    cardNames[i] = [];
    for (j = l = 1; l <= 9; j = l += 1) {
      cardNames[i][j] = createCardName();
    }
  }
  console.log(cardNames);
  resetCards();
  res.render('randomcard', {
    cardNames: cardNames
  });
});

module.exports = router;
