// Generated by CoffeeScript 1.10.0
var createCardName, express, router;

express = require('express');

router = express.Router();

router.route('/randomcard').get(function(req, res) {
  var cardName;
  cardName = createCardName();
  res.render('randomcard', {
    cardName: cardName
  });
});

createCardName = function() {
  var cardNumber, suitNames, suitNumber;
  suitNames = ["club", "dmnd", "hart", "spad", "joke"];
  suitNumber = Math.ceil(Math.random() * 4);
  cardNumber = suitNumber < 4 ? Math.ceil(Math.random() * 12) : Math.ceil(Math.random() * 2);
  console.log(suitNames[suitNumber], cardNumber, suitNumber);
  return suitNames[suitNumber] + cardNumber;
};

module.exports = router;
